---
- name: ensure workshop folder {{ ibmis_name_prefix }} exists
  file:
    path: "{{ playbook_dir }}/{{ ibmis_name_prefix }}"
    state: directory

## These Cloud resources are used for every workshop type
## This includes VPC, subnet, Security Group, Internet Gateway and route table
## TODO: adopt for IBM cloud
- name: provision IBM cloud resources
  include_tasks: resources/resources.yml

## TODO: figure out a way to get the "image"" for the "ibm_is_instance" module
## TODO: compare with example here: https://github.com/IBM-Cloud/ansible-collection-ibm/blob/3b7c95bfa1b3a3821b38366ee6f5756e90740ee7/examples/simple-vm-ssh/create.yml#L50-L52
## TODO: check if "ibm_is_images_info" is the right module here or another one is better
- name: find ami for ansible control node
  ibm_is_images_info:
    region: "{{ ec2_region }}"
    owners: "{{ ec2_info[control_type].owners }}"
    filters:
      name: "{{ ec2_info[control_type].filter }}"
      architecture: "{{ ec2_info[control_type].architecture }}"
  register: amis

# TODO: compare to https://github.com/IBM-Cloud/ansible-collection-ibm/blob/master/examples/simple-vm-ssh/create.yml#L54-L58
- name: save ami for ansible control node
  set_fact:
    ansible_control_node_ami: >
      {{ amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}

## TODO: check out TODOs in cluster_instances.yml
- name: Create the control clusters
  include_tasks: cluster_instances.yml
  loop: "{{ range(1, control_nodes|default(1) + 1 ) | list }}"
  loop_control:
    loop_var: sequence

## find AMI - amazon machine images dynamically
## TODO: again modify to fit IBM cloud, see above
- name: find correct AMI
  include_tasks: 'ami_find/ami_find_{{ workshop_type }}.yml'

## TODO: again modify to fit IBM cloud, see above
## Instance creation
- name: provision workshop instances
  include_tasks: 'instances/instances_{{ workshop_type }}.yml'

- name: create instructor_inventory, and student files
  include_tasks: create_inventory.yml
