---
## TODO: fix paramters to work with the IBM cloud module
- name: Create IBM VPC {{ ibmis_name_prefix }}-vpc
  ibm_is_vpc:
    name: "{{ ibmis_name_prefix }}-vpc"
    tags:
      Username: "{{ ibmcloud_user }}"
      Info: "Username that provisioned this-> {{ ibmcloud_user }}"
      Linklight: "This was provisioned through the linklight provisioner"
      Students: "{{ student_total }}"
      Workshop_type: "{{ workshop_type }}"
      Workshop: "{{ ibmis_name_prefix }}"
  register: create_vpc
  until: create_vpc is not failed
  retries: 5

## TODO: fix paramters to work with the IBM cloud module
- name: Create subnet for {{ ibmis_name_prefix }}-vpc
  ibm_is_subnet:
    region: "{{ ec2_region }}"
    az: "{{ ec2_az }}"
    vpc_id: "{{ create_vpc.vpc.id }}"
    cidr: "{{ ec2_subnet }}"
    wait_timeout: 600
    resource_tags:
      Name: "{{ ec2_name_prefix }}-subnet"
      Username: "{{ aws_user }}"
      Info: "Username that provisioned this-> {{ aws_user }}"
      Linklight: "This was provisioned through the linklight provisioner"
      Students: "{{ student_total }}"
      Workshop_type: "{{ workshop_type }}"
      Workshop: "{{ ec2_name_prefix }}"
  register: create_subnet
  until: create_subnet is not failed
  retries: 15

## TODO: fix paramters to work with the IBM cloud module
- name: Create ssh key pair for workshop {{ eibmis_name_prefix }}
  ibm_is_ssh_key:
    name: "{{ ec2_name_prefix }}-key"
    region: "{{ ec2_region }}"
  register: create_key

## TODO: ensure this works, see https://github.com/IBM-Cloud/ansible-collection-ibm/blob/3b7c95bfa1b3a3821b38366ee6f5756e90740ee7/examples/simple-vm-ssh/create.yml#L45 for example
- name: save private key
  copy:
    content: "{{ create_key.resource }}"
    dest: "{{ playbook_dir }}/{{ ibmis_name_prefix }}/{{ ibmis_name_prefix }}-private.pem"
    mode: '0400'
  when: create_key.changed

- name: Ensure key file has proper permissions
  file:
    dest: "{{ playbook_dir }}/{{ ibmis_name_prefix }}/{{ ibmis_name_prefix }}-private.pem"
    mode: 0600
