---
###############################################################################
# NOTE: YOU MUST UPDATE THIS EVERY TIME WE UPDATE THE QRADAR AMI
#
# This is a limitation of the QRadar installation setup, it is not made to
# handle ephemeral ip addresses on instance spin up so we have to do post
# deploy fixes
#
###############################################################################
- name: QRadar Post Instance Deployment Configuration
  hosts: qradar
  become: true
  vars:
    qradar_config_files_with_ip_addrs:
      - "/etc/consul/consul.json"
      - "/etc/consul/zk-consul.json"
      - "/etc/consul/qregistry.json"
      - "/etc/hosts"
      - "/etc/hosts.bak"
      - "/etc/hosts.default"
      - "/etc/httpd/conf/httpd.conf"
      - "/etc/si/install_config/ip"
      - "/etc/sysconfig/marathon"
      - "/etc/sysconfig/network"
      - "/etc/sysconfig/iptables"
      - "/etc/sysconfig/mesos-master"
      - "/etc/sysconfig/mesos-agent"
      - "/etc/syslog-ng/syslog-ng.conf"
      - "/etc/systemd/system/docker.service.d/10-options.conf"
      - "/etc/zookeeper/conf/zoo.cfg"
      - "/opt/qradar/conf/nva.conf"
      - "/opt/qradar/conf/nva.hostcontext.conf"
      - "/opt/qradar/conf/iptables.d/nat.post/0_docker_nat"
      - "/opt/qradar/conf/iptables.d/nat.post/0_docker_infra_nat"
      - "/opt/qradar/conf/iptables.d/nat.post/0_docker_apps_nat"
      - "/opt/qradar/conf/iptables.d/nat.post/0_docker_apps_proxy_nat"
      - "/opt/qradar/conf/nva.conf.bak"
      - "/opt/qradar/conf/frameworks.properties"
      - "/opt/qradar/conf/capabilities/hostcapabilities.xml"
      - "/opt/qradar/conf/capabilities/reported_hostcapabilties.xml"
      - "/opt/qradar/conf/.ipaddress"
      - "/opt/qradar/conf/distrib_config.xml"
      - "/opt/qradar/conf/frameworks.properties.bak"
      - "/opt/qradar/conf/oauth_server.cache"
      - "/opt/qradar/conf/dtlspki/certs/10.pem"
      - "/opt/qradar/conf/dtlspki/172.16.233.181/server/server_ssl.cnf"
      - "/opt/qradar/conf/dtlspki/index.txt"
      - "/opt/qradar/conf/install_dump.txt.bak"
      - "/opt/qradar/conf/install_instructions.txt.bak"
      - "/opt/qradar/conf/configmetadata.xml"
      - "/opt/qradar/conf/deployment.xml"
      - "/opt/qradar/conf/ifmapConfig.xml"
      - "/opt/qradar/conf/EP.xml"
      - "/opt/qradar/conf/nva.masterdaemon.masterdaemon.conf"
      - "/opt/qradar/conf/nva.qflow.qflow0.conf"
      - "/opt/qradar/conf/syslog-ng.conf"
      - "/opt/qradar/conf/collectorlist.conf"
      - "/opt/qradar/dca/dca/init/dca_license/dca_license_settings_user.txt"
      - "/opt/qradar/dca/dca/init/dca_update/dca_update_settings_user.txt"
    qradar_netconf_status_file: "/opt/qradar/workshop_provision_ip_configured"
  tasks:
    - name: Check if status file exists
      stat:
        path: "{{ qradar_netconf_status_file }}"
      register: st

    - name: Configure IP address if necessary
      block:
        - name: stop hostcontext
          service:
            name: hostcontext
            state: stopped
        - name: stop tomcat
          service:
            name: tomcat
            state: stopped
        - name: stop hostservices
          service:
            name: hostservices
            state: stopped
        - name: Replace all mentions of Instance IP used to create custom AMI
          replace:
            path: '{{ item }}'
            regexp: '172\.16\.233\.181'
            replace: '{{ private_ip }}'
          loop: "{{ qradar_config_files_with_ip_addrs }}"
          register: dot_notation
        - name: Replace all mentions of Instance IP in dash notation used to create custom AMI
          replace:
            path: '{{ item }}'
            regexp: '172-16-233-181'
            replace: '{{ private_ip | regex_replace( "\.", "-" ) }}'
          loop: "{{ qradar_config_files_with_ip_addrs }}"
          register: dash_notation

        - name: check for old dtlspki ssl conf dir
          stat:
            path: /opt/qradar/conf/dtlspki/172.16.233.181/
          register: old_dtlspki_ssl_conf_dir

        - name: move dtlspki ssl conf dir
          shell: "mv /opt/qradar/conf/dtlspki/172.16.233.181/ /opt/qradar/conf/dtlspki/{{private_ip}}/"
          args:
            creates: "/opt/qradar/conf/dtlspki/{{private_ip}}/"
          when: old_dtlspki_ssl_conf_dir.stat.exists

        - name: restart iptables
          service:
            name: iptables
            state: restarted
        - name: restart httpd
          service:
            name: httpd
            state: restarted
        - name: restart imq
          service:
            name: imq
            state: restarted
        - name: start hostservices
          service:
            name: hostservices
            state: started
        - name: start tomcat
          service:
            name: tomcat
            state: started
        - name: hostcontext tomcat
          service:
            name: hostcontext
            state: started
        - name: restart consul
          service:
            name: consul
            state: restarted
        - name: Create status file
          file:
            path: "{{ qradar_netconf_status_file }}"
            state: touch
      when:
        - not st.stat.exists


